// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

package packet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet_ContentType int32

const (
	Packet_TEXT      Packet_ContentType = 0
	Packet_IMAGE     Packet_ContentType = 1
	Packet_VIDEO     Packet_ContentType = 2
	Packet_VOICE     Packet_ContentType = 3
	Packet_NEWS      Packet_ContentType = 4
	Packet_DECLARE   Packet_ContentType = 5
	Packet_MUSIC     Packet_ContentType = 6
	Packet_BROADCAST Packet_ContentType = 7
	Packet_OTHER     Packet_ContentType = 8
)

var Packet_ContentType_name = map[int32]string{
	0: "TEXT",
	1: "IMAGE",
	2: "VIDEO",
	3: "VOICE",
	4: "NEWS",
	5: "DECLARE",
	6: "MUSIC",
	7: "BROADCAST",
	8: "OTHER",
}

var Packet_ContentType_value = map[string]int32{
	"TEXT":      0,
	"IMAGE":     1,
	"VIDEO":     2,
	"VOICE":     3,
	"NEWS":      4,
	"DECLARE":   5,
	"MUSIC":     6,
	"BROADCAST": 7,
	"OTHER":     8,
}

func (x Packet_ContentType) String() string {
	return proto.EnumName(Packet_ContentType_name, int32(x))
}

func (Packet_ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0, 0}
}

type Packet struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

type Packet_Head struct {
	HPorotolType         uint32   `protobuf:"varint,1,opt,name=hPorotolType,proto3" json:"hPorotolType,omitempty"`
	HOperationType       uint32   `protobuf:"varint,2,opt,name=hOperationType,proto3" json:"hOperationType,omitempty"`
	HMsgBodyLength       uint64   `protobuf:"varint,3,opt,name=hMsgBodyLength,proto3" json:"hMsgBodyLength,omitempty"`
	HMsgID               uint64   `protobuf:"varint,4,opt,name=hMsgID,proto3" json:"hMsgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet_Head) Reset()         { *m = Packet_Head{} }
func (m *Packet_Head) String() string { return proto.CompactTextString(m) }
func (*Packet_Head) ProtoMessage()    {}
func (*Packet_Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0, 0}
}

func (m *Packet_Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_Head.Unmarshal(m, b)
}
func (m *Packet_Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_Head.Marshal(b, m, deterministic)
}
func (m *Packet_Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_Head.Merge(m, src)
}
func (m *Packet_Head) XXX_Size() int {
	return xxx_messageInfo_Packet_Head.Size(m)
}
func (m *Packet_Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_Head proto.InternalMessageInfo

func (m *Packet_Head) GetHPorotolType() uint32 {
	if m != nil {
		return m.HPorotolType
	}
	return 0
}

func (m *Packet_Head) GetHOperationType() uint32 {
	if m != nil {
		return m.HOperationType
	}
	return 0
}

func (m *Packet_Head) GetHMsgBodyLength() uint64 {
	if m != nil {
		return m.HMsgBodyLength
	}
	return 0
}

func (m *Packet_Head) GetHMsgID() uint64 {
	if m != nil {
		return m.HMsgID
	}
	return 0
}

type Packet_Body struct {
	BType                uint32             `protobuf:"varint,1,opt,name=bType,proto3" json:"bType,omitempty"`
	BAction              string             `protobuf:"bytes,2,opt,name=bAction,proto3" json:"bAction,omitempty"`
	BContentType         Packet_ContentType `protobuf:"varint,3,opt,name=bContentType,proto3,enum=Packet_ContentType" json:"bContentType,omitempty"`
	BContent             *Packet_Content    `protobuf:"bytes,4,opt,name=bContent,proto3" json:"bContent,omitempty"`
	BTimestamp           uint64             `protobuf:"varint,5,opt,name=bTimestamp,proto3" json:"bTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Packet_Body) Reset()         { *m = Packet_Body{} }
func (m *Packet_Body) String() string { return proto.CompactTextString(m) }
func (*Packet_Body) ProtoMessage()    {}
func (*Packet_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0, 1}
}

func (m *Packet_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_Body.Unmarshal(m, b)
}
func (m *Packet_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_Body.Marshal(b, m, deterministic)
}
func (m *Packet_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_Body.Merge(m, src)
}
func (m *Packet_Body) XXX_Size() int {
	return xxx_messageInfo_Packet_Body.Size(m)
}
func (m *Packet_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_Body proto.InternalMessageInfo

func (m *Packet_Body) GetBType() uint32 {
	if m != nil {
		return m.BType
	}
	return 0
}

func (m *Packet_Body) GetBAction() string {
	if m != nil {
		return m.BAction
	}
	return ""
}

func (m *Packet_Body) GetBContentType() Packet_ContentType {
	if m != nil {
		return m.BContentType
	}
	return Packet_TEXT
}

func (m *Packet_Body) GetBContent() *Packet_Content {
	if m != nil {
		return m.BContent
	}
	return nil
}

func (m *Packet_Body) GetBTimestamp() uint64 {
	if m != nil {
		return m.BTimestamp
	}
	return 0
}

type Packet_Content struct {
	CToID                string   `protobuf:"bytes,1,opt,name=cToID,proto3" json:"cToID,omitempty"`
	CFromID              string   `protobuf:"bytes,2,opt,name=cFromID,proto3" json:"cFromID,omitempty"`
	CContext             string   `protobuf:"bytes,3,opt,name=cContext,proto3" json:"cContext,omitempty"`
	CFlag                uint64   `protobuf:"varint,4,opt,name=cFlag,proto3" json:"cFlag,omitempty"`
	COther               string   `protobuf:"bytes,5,opt,name=cOther,proto3" json:"cOther,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet_Content) Reset()         { *m = Packet_Content{} }
func (m *Packet_Content) String() string { return proto.CompactTextString(m) }
func (*Packet_Content) ProtoMessage()    {}
func (*Packet_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0, 2}
}

func (m *Packet_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_Content.Unmarshal(m, b)
}
func (m *Packet_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_Content.Marshal(b, m, deterministic)
}
func (m *Packet_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_Content.Merge(m, src)
}
func (m *Packet_Content) XXX_Size() int {
	return xxx_messageInfo_Packet_Content.Size(m)
}
func (m *Packet_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_Content proto.InternalMessageInfo

func (m *Packet_Content) GetCToID() string {
	if m != nil {
		return m.CToID
	}
	return ""
}

func (m *Packet_Content) GetCFromID() string {
	if m != nil {
		return m.CFromID
	}
	return ""
}

func (m *Packet_Content) GetCContext() string {
	if m != nil {
		return m.CContext
	}
	return ""
}

func (m *Packet_Content) GetCFlag() uint64 {
	if m != nil {
		return m.CFlag
	}
	return 0
}

func (m *Packet_Content) GetCOther() string {
	if m != nil {
		return m.COther
	}
	return ""
}

func init() {
	proto.RegisterEnum("Packet_ContentType", Packet_ContentType_name, Packet_ContentType_value)
	proto.RegisterType((*Packet)(nil), "Packet")
	proto.RegisterType((*Packet_Head)(nil), "Packet.Head")
	proto.RegisterType((*Packet_Body)(nil), "Packet.Body")
	proto.RegisterType((*Packet_Content)(nil), "Packet.Content")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_e9ef1a6541f9f9e7) }

var fileDescriptor_e9ef1a6541f9f9e7 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xcb, 0x6e, 0xdb, 0x30,
	0x10, 0xac, 0x12, 0xca, 0xb6, 0x56, 0x4e, 0x4a, 0x30, 0x41, 0x21, 0xe8, 0x50, 0x04, 0x3e, 0x14,
	0x01, 0x0a, 0xf8, 0x90, 0x1e, 0x7a, 0xd6, 0x83, 0x69, 0x04, 0xc4, 0x95, 0x41, 0xab, 0x8f, 0xab,
	0xa4, 0x10, 0x56, 0xd0, 0x58, 0x14, 0x64, 0x1e, 0x9a, 0x73, 0xff, 0xa0, 0xdf, 0xd3, 0x0f, 0xe9,
	0xe7, 0x04, 0x5c, 0x49, 0x81, 0xec, 0x1b, 0x67, 0x76, 0x96, 0x3b, 0xb3, 0x58, 0x98, 0x37, 0x79,
	0xf9, 0x4b, 0xea, 0x65, 0xd3, 0x2a, 0xad, 0x16, 0xff, 0x09, 0x4c, 0xd6, 0x48, 0xf8, 0x7f, 0x2d,
	0x20, 0x77, 0x32, 0x7f, 0x60, 0x0b, 0x98, 0x57, 0x6b, 0x65, 0xca, 0x4f, 0xd9, 0x73, 0x23, 0x3d,
	0xeb, 0xca, 0xba, 0x3e, 0x13, 0x07, 0x1c, 0xfb, 0x00, 0xe7, 0x55, 0xda, 0xc8, 0x36, 0xd7, 0x8f,
	0xaa, 0x46, 0xd5, 0x09, 0xaa, 0x8e, 0x58, 0xd4, 0xad, 0xf6, 0xdb, 0x50, 0x3d, 0x3c, 0xdf, 0xcb,
	0x7a, 0xab, 0x2b, 0xef, 0xf4, 0xca, 0xba, 0x26, 0xe2, 0x88, 0x65, 0xef, 0x60, 0x62, 0x98, 0x24,
	0xf6, 0x08, 0xd6, 0x7b, 0xe4, 0xff, 0xb3, 0x80, 0x18, 0x19, 0xbb, 0x04, 0xbb, 0x18, 0xb9, 0xe9,
	0x00, 0xf3, 0x60, 0x5a, 0x04, 0xa5, 0x99, 0x86, 0xf3, 0x1d, 0x31, 0x40, 0xf6, 0x19, 0xe6, 0x45,
	0xa4, 0x6a, 0x2d, 0x6b, 0x8d, 0x6d, 0x66, 0xec, 0xf9, 0xcd, 0xc5, 0xb2, 0x0b, 0xbb, 0x1c, 0x95,
	0xc4, 0x81, 0x90, 0x7d, 0x84, 0xd9, 0x80, 0xd1, 0x8b, 0x7b, 0xf3, 0xf6, 0xa8, 0x49, 0xbc, 0x0a,
	0xd8, 0x7b, 0x80, 0x22, 0x7b, 0xdc, 0xc9, 0xbd, 0xce, 0x77, 0x8d, 0x67, 0xa3, 0xf5, 0x11, 0xe3,
	0xff, 0xb1, 0x60, 0x3a, 0x68, 0x2f, 0xc1, 0x2e, 0x33, 0x95, 0xc4, 0x98, 0xc0, 0x11, 0x1d, 0x30,
	0x09, 0xca, 0xdb, 0x56, 0xed, 0x92, 0x78, 0x48, 0xd0, 0x43, 0xe6, 0xc3, 0xac, 0xc4, 0xde, 0xdf,
	0x1a, 0xdd, 0x3b, 0xe2, 0x15, 0xe3, 0x5f, 0xb7, 0x4f, 0xf9, 0xb6, 0xdf, 0x56, 0x07, 0xcc, 0x12,
	0xcb, 0x54, 0x57, 0xb2, 0x45, 0x27, 0x8e, 0xe8, 0xd1, 0x42, 0x83, 0x3b, 0x4e, 0x38, 0x03, 0x92,
	0xf1, 0x9f, 0x19, 0x7d, 0xc3, 0x1c, 0xb0, 0x93, 0x55, 0xf0, 0x85, 0x53, 0xcb, 0x3c, 0xbf, 0x27,
	0x31, 0x4f, 0xe9, 0x09, 0x3e, 0xd3, 0x24, 0xe2, 0xf4, 0xd4, 0x48, 0xbf, 0xf2, 0x1f, 0x1b, 0x4a,
	0x98, 0x0b, 0xd3, 0x98, 0x47, 0xf7, 0x81, 0xe0, 0xd4, 0x36, 0x8a, 0xd5, 0xb7, 0x4d, 0x12, 0xd1,
	0x09, 0x3b, 0x03, 0x27, 0x14, 0x69, 0x10, 0x47, 0xc1, 0x26, 0xa3, 0x53, 0x53, 0x49, 0xb3, 0x3b,
	0x2e, 0xe8, 0x2c, 0xbc, 0x00, 0xa2, 0xe5, 0x5e, 0x87, 0x6e, 0xb7, 0xbd, 0xb5, 0x39, 0x9e, 0x62,
	0x82, 0x67, 0xf7, 0xe9, 0x25, 0x00, 0x00, 0xff, 0xff, 0x36, 0xda, 0xe4, 0x5c, 0x86, 0x02, 0x00,
	0x00,
}
